# Copyright © 2022-2023 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
linters-settings:
  misspell:
    locale: US
linters:
  enable:
    - bodyclose
    - errcheck
    - goconst
    - govet
    - gosimple
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
  disable-all: true
  fast: true
