# Copyright © 2023 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
version: '3.7'

volumes:
  portainer_data:

services:
  portainer:
    image:  portainer/portainer-ce
    container_name: portainer
    ports:
      - "127.0.0.1:9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: "on-failure:5"
