---

# Copyright © 2023 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

version: '3.4'

services:

#################################################################
# Automated Vending Microservices
#################################################################

  # this device service must be run as root to mount the device
  ds-card-reader:
    user: "0:0"
    devices:
      - /dev/input:/dev/input
    environment:
      DRIVERCONFIG_SIMULATEDEVICE: "false"
      DRIVERCONFIG_DEVICESEARCHPATH: "/dev/input/event*"
      DRIVERCONFIG_VID: 65535 # 0xFFFF
      DRIVERCONFIG_PID: 53    # 0x0035
...
