# Copyright © 2023 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

MaxEventSize: 0
Writable:
  LogLevel: INFO
  InsecureSecrets:
    DB:
      path: redisdb
      Secrets:
        username: ''
        password: ''
  Reading:
    ReadingUnits: true
Service:
  HealthCheckInterval: 10s
  Host: localhost
  ServerBindAddr: ''
  Port: 48098
  StartupMsg: Card Reader device service started
  MaxRequestSize: 0
  RequestTimeout: 5s
  CORSConfiguration:
    EnableCORS: false
    CORSAllowCredentials: false
    CORSAllowedOrigin: 'https://localhost'
    CORSAllowedMethods: 'GET, POST, PUT, PATCH, DELETE'
    CORSAllowedHeaders: >-
      Authorization, Accept, Accept-Language, Content-Language, Content-Type,
      X-Correlation-ID
    CORSExposeHeaders: >-
      Cache-Control, Content-Language, Content-Length, Content-Type, Expires,
      Last-Modified, Pragma, X-Correlation-ID
    CORSMaxAge: 3600
Registry:
  Host: localhost
  Port: 8500
  Type: consul
Clients:
  core-data:
    Protocol: http
    Host: localhost
    Port: 59880
  core-metadata:
    Protocol: http
    Host: localhost
    Port: 59881
DriverConfig:
  DeviceName: card-reader
  DeviceSearchPath: ''
  VID: 0
  PID: 0
  SimulateDevice: true
Device:
  DataTransform: true
  MaxCmdOps: 128
  MaxCmdValueLen: 256
  ProfilesDir: ./res/profiles
  DevicesDir: ./res/devices
  EnableAsyncReadings: true
  AsyncBufferSize: 16
  Labels: []
  Discovery:
    Enabled: false
    Interval: 30s
MessageBus:
  Protocol: tcp
  Host: localhost
  Port: 1883
  Type: mqtt
  AuthMode: none
  BaseTopicPrefix: edgex
  Optional:
    ClientId: ds-card-reader
    Qos: '0'
    KeepAlive: '10'
    Retained: 'false'
    AutoReconnect: 'true'
    ConnectTimeout: '5'
    SkipCertVerify: 'false'
