name: Integration Test
on: workflow_dispatch
# on:
#   push:
#     branches:
#     - master
#   pull_request:

permissions:
  contents: read

jobs:
  build_docker:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Install go
            uses: actions/setup-go@v4
            with:
              go-version: '1.20'
          - name: Make Docker images
            run: |
              make docker
              make run
              sleep 15
              mkdir -p "$PWD"/test_results && bash smoke-test.sh > "$PWD"/test_results/results.txt
          - uses: actions/upload-artifact@v3
            with:
              name: test_results
              path: ${{ github.workspace }}/test_results/
