# Copyright © 2022 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

[Writable]
LogLevel = 'INFO'
    [Writable.InsecureSecrets]
        [Writable.InsecureSecrets.DB]
        path = "redisdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = ""
            password = ""


[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 48094
ReadMaxLimit = 100
StartupMsg = 'This EdgeX application service reads events from a controller board device service and propagates the information from the controller board to other services and API endpoints'
RequestTimeout = '30s'
MaxRequestSize = 0
ServerBindAddr = ""
MaxResultCount = 0

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Trigger]
Type="edgex-messagebus"
  [Trigger.EdgexMessageBus]
  Type = "mqtt"
    [Trigger.EdgexMessageBus.SubscribeHost]
    Host = "localhost"
    Port = 1883
    Protocol = "tcp"
    SubscribeTopics="edgex/events/#"
    [Trigger.EdgexMessageBus.Optional]
    authmode = "none"
    ClientId ="as-controller-board-status"
    Qos =  "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive =  "10" # Seconds (must be 2 or greater)
    Retained = "false"
    AutoReconnect = "true"
    ConnectTimeout = "5" # Seconds
    SkipCertVerify = "false"

[Clients]
  # Used for version check on start-up
  # Also used for DeviceService, DeviceProfile and Device clients
  [Clients.core-metadata]
  Protocol = "http"
  Host = "localhost"
  Port = 59881

  # Used for Notification and Subscription clients
  [Clients.support-notifications]
  Protocol = "http"
  Host = "localhost"
  Port = 59860

[ApplicationSettings]
  AverageTemperatureMeasurementDuration = "-15s"
  DeviceName = "controller-board"
  MaxTemperatureThreshold = "83"
  MinTemperatureThreshold = "10"
  DoorStatusCommandEndpoint = "http://localhost:59882/api/v2/device/name/Inference-device/inferenceDoorStatus"
  NotificationCategory = "HW_HEALTH"
  NotificationEmailAddresses = "your-email@site.com"
  NotificationLabels = "HW_HEALTH"
  NotificationReceiver = "SystemAdministrator"
  NotificationSender = "AutomatedCheckoutMaintenanceNotification"
  NotificationSeverity = "CRITICAL"
  NotificationName = "maintenance-notification"
  NotificationSubscriptionMaxRESTRetries = "10"
  NotificationSubscriptionRESTRetryInterval = "10s"
  NotificationThrottleDuration = "1m"
  SubscriptionAdminState = "UNLOCKED"
  RESTCommandTimeout = "15s"
  VendingEndpoint = "http://localhost:59860/boardStatus"
