name: Integration Test

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build_docker:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Install go
            uses: actions/setup-go@v4
            with:
              go-version: '1.20'
          - name: Make Docker images
            run: |
              make docker
              make run-base
              sleep 15
              cd automated-vending && mkdir -p "$PWD"/test_results && go run main.go > "$PWD"/test_results/results.txt
          - uses: actions/upload-artifact@v3
            with:
              name: test_results
              path: ${{ github.workspace }}/test_results/
